apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: affiliate-junction
  labels:
    app.kubernetes.io/name: affiliate-junction
    app.kubernetes.io/component: web-ui
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: affiliate-junction
    app.kubernetes.io/component: web-ui
  ports:
    - name: http
      port: 10000
      targetPort: 10000
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

# Made with Bob
